# Generated by Django 5.0.4 on 2024-04-21 22:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_tawjihi', '0002_classe_professeur_matiere_professeur'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classe',
            name='professeur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_tawjihi.prof'),
        ),
        migrations.AlterField(
            model_name='matiere',
            name='professeur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_tawjihi.prof'),
        ),
    ]
