# Generated by Django 5.0.4 on 2024-04-23 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_tawjihi', '0003_alter_classe_professeur_alter_matiere_professeur'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classe',
            name='fk_niveau',
        ),
        migrations.RemoveField(
            model_name='classe',
            name='professeur',
        ),
        migrations.RemoveField(
            model_name='etudiant',
            name='fk_classe',
        ),
        migrations.RemoveField(
            model_name='note',
            name='fk_etudiant',
        ),
        migrations.RemoveField(
            model_name='matiere',
            name='professeur',
        ),
        migrations.RemoveField(
            model_name='note',
            name='fk_matiere',
        ),
        migrations.RemoveField(
            model_name='note',
            name='fk_prof',
        ),
        migrations.DeleteModel(
            name='Niveau',
        ),
        migrations.DeleteModel(
            name='Classe',
        ),
        migrations.DeleteModel(
            name='Etudiant',
        ),
        migrations.DeleteModel(
            name='Matiere',
        ),
        migrations.DeleteModel(
            name='Note',
        ),
        migrations.DeleteModel(
            name='Prof',
        ),
    ]
