# Generated by Django 5.0.4 on 2024-04-30 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_tawjihi', '0005_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etudiant',
            name='cne',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
