# Generated by Django 5.0.4 on 2024-04-30 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_tawjihi', '0006_alter_etudiant_cne'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etudiant',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
