# Generated by Django 5.0.4 on 2024-04-30 16:08

from django.db import migrations,models


class Migration(migrations.Migration):

    dependencies = [
        ('app_tawjihi', '0007_alter_etudiant_id'),
    ]

    operations = [
        migrations.AlterField(
        model_name='etudiant',
        name='id',
        field=models.BigAutoField(primary_key=True, serialize=False),
    ),
    migrations.AlterField(
        model_name='etudiant',
        name='cne',
        field=models.CharField(max_length=10, unique=True),
    ),
    ]
