# Generated by Django 5.0.4 on 2024-04-30 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_tawjihi', '0008_auto_20240430_1708'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classe',
            name='fk_niveau',
        ),
        migrations.RemoveField(
            model_name='classe',
            name='professeur',
        ),
        migrations.RemoveField(
            model_name='etudiant',
            name='fk_classe',
        ),
        migrations.RemoveField(
            model_name='note',
            name='fk_etudiant',
        ),
        migrations.RemoveField(
            model_name='note',
            name='fk_matiere',
        ),
        migrations.RemoveField(
            model_name='prof',
            name='matiere',
        ),
        migrations.RemoveField(
            model_name='note',
            name='fk_prof',
        ),
        migrations.DeleteModel(
            name='Niveau',
        ),
        migrations.DeleteModel(
            name='Classe',
        ),
        migrations.DeleteModel(
            name='Etudiant',
        ),
        migrations.DeleteModel(
            name='Matiere',
        ),
        migrations.DeleteModel(
            name='Note',
        ),
        migrations.DeleteModel(
            name='Prof',
        ),
    ]
