# Generated by Django 5.0.4 on 2024-04-30 20:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_tawjihi', '0010_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='matiere',
            name='fk_classe',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app_tawjihi.classe'),
            preserve_default=False,
        ),
    ]
