# Generated by Django 5.0.4 on 2024-04-30 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_tawjihi', '0011_matiere_fk_classe'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matiere',
            name='fk_classe',
        ),
        migrations.AddField(
            model_name='classe',
            name='matieres',
            field=models.ManyToManyField(related_name='classes', to='app_tawjihi.matiere'),
        ),
    ]
