# Generated by Django 5.0.4 on 2024-04-30 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_tawjihi', '0012_remove_matiere_fk_classe_classe_matieres'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classe',
            name='matieres',
        ),
    ]
