# Generated by Django 5.0.4 on 2024-05-03 12:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_tawjihi', '0014_classe_matieres'),
    ]

    operations = [
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('continue_in_school', models.BooleanField(default=True)),
                ('reason_for_choice', models.TextField(blank=True, null=True)),
                ('dream_job', models.TextField(blank=True, null=True)),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_tawjihi.etudiant')),
                ('niveau', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_tawjihi.niveau')),
            ],
        ),
    ]
